function include_transform(varargin)
% fidout, filename, id*off, (tranid)
fidout=varargin{1};
arg1=varargin{2};
arg2=varargin{3};
if nargin==4
    arg3=varargin{4};
else
    arg3=0;
end
num=5;

tags={'$# filename','','','','','','','';...
      '$#  idnoff','ideoff','idpoff','idmoff','idsoff','idfoff','iddoff','';...
      '$#  idroff','','','','','','','';...
      '$#  fctmas','fcttim','fctlen','fcttem','incout1','','','';...
      '$#  tranid','','','','','','','';...
     };
 formats={'%s','','','','','','','';...
          '%10i','%10i','%10i','%10i','%10i','%10i','%10i','';...
          '%10i','','','','','','','';...
          '% #10g','% #10g','% #10g','% #10g','%10i','','','';...
          '%10i','','','','','','','';...
         };
values={arg1,'','','','','','','';...
        arg2,arg2,arg2,arg2,arg2,arg2,arg2,'';...
        arg2,'','','','','','','';...
        1,1,1,1,0,'','','';...
        arg3,'','','','','','','';...
       };
   
fprintf(fidout,'$\n');
fprintf(fidout,'*INCLUDE_TRANSFORM\n');
for ii=1:num
     prt=find(~cellfun(@isempty,tags(ii,:)));                     % get indexes of nonempty elements of a current (ii) line of <fun>
    fprintf(fidout,'%10s',tags{ii,prt}); fprintf(fidout,'\n');   % print tags
    for jj=1:length(prt)                                        % according to the number of nonempty elements
        fprintf(fidout,formats{ii,jj},values{ii,jj});                  % print values in the format
    end
    fprintf(fidout,'\n');                                       % jump to next line
end
