*CONSTRAINED_JOINT_REVOLUTE_ID
$#     jid                                                                 title
       222                                                                      
$#      n1        n2        n3        n4        n5        n6       rps      damp
    202100    202200    202101    202201         0         0  1.000000  1.000000
*CONSTRAINED_JOINT_REVOLUTE_ID
       232                                                                      
    203100    203200    203101    203201         0         0  1.000000  1.000000
*CONSTRAINED_JOINT_REVOLUTE_ID
       322                                                                      
    302100    302200    302101    302201         0         0  1.000000  1.000000